### ISSUE TITLE
Assert read positions in layout

### ISSUE THREAD

**Issue by skoren** [maickrau/verkko#29]
In /data/Phillippy/hpgp/tobias_test_data/test_correction/bri_asm/6-layoutContigs. I get an error with both:

```
  File "/data/korens/devel/verkko/scripts/get_layout_from_mbg.py", line 112, in get_matches
    assert read_end_pos > read_start_pos
```
and
```
Traceback (most recent call last):
  File "/data/korens/devel/hybrid-assembly/scripts/get_layout_from_mbg.py", line 267, in <module>
    assert readstart < readend
```

This looks like it is due to a few 0-length gaps:
```
269bd9cd-dc08-424a-b411-e590c342fa48    88855   27250   27250   +       <gapont-182-len-0-cov-5 2       0       2       2       2       60
afbfa81d-c456-465f-9430-5d810af607ff    218418  69365   69365   +       <gapont-182-len-0-cov-5 2       0       2       2       2       60
7c51bcb1-2d0a-4f02-b14c-5253a2ffc9ae    150774  36176   36176   +       <gapont-182-len-0-cov-5 2       0       2       2       2       60
```

**Comment by skoren** [comment]
Workaround committed to runverkko: https://github.com/brianwalenz/runverkko/commit/b5030d14e7805fda0cff98d8053467b0d03f4d9e

**Comment by skoren** [comment]
Resolved with gap filling changes
